### ISSUE TITLE
The processed dataset is not available

### ISSUE THREAD

**Issue by Shraban123** [xiransong/xGCN#2]
The link to download the processed dataset does not work. Can you please fix it or share an alternative link...

**Comment by xiransong** [comment]
Hi! The link is ok now. And welcome to use our refactored XGCN package: https://xgcn.readthedocs.io/en/latest/index.html

**Comment by Shraban123** [comment]
Can you share the XBox dataset used in the paper so that I can run the code on the dataset.

**Comment by Shraban123** [comment]
> Hi! The link is ok now. And welcome to use our refactored XGCN package: https://xgcn.readthedocs.io/en/latest/index.html

Thanks a lot for your reply.

**Comment by xiransong** [comment]
Hi! We change to use Google Drive for the datasets download. See https://xgcn.readthedocs.io/en/latest/user_guide/usage_examples/example_pokec_livejournal.html
The Xbox dataset is an industrial one and is not able to be public.
